server:
  port: 8201
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/smart_cms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 12345678
  redis:
    database: 1
    port: 6379
    host: localhost
    password:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: bosen-auth
          uri: lb://bosen-auth
          predicates:
            - Path=/bosen-auth/**
          filters:
            - StripPrefix=1
        - id: bosen-admin
          uri: lb://bosen-admin
          predicates:
            - Path=/bosen-admin/**
          filters:
            - StripPrefix=1
        - id: bosen-member
          uri: lb://bosen-member
          predicates:
            - Path=/bosen-member/**
          filters:
            - StripPrefix=1
        - id: bosen-search
          uri: lb://bosen-search
          predicates:
            - Path=/bosen-search/**
          filters:
            - StripPrefix=1
        - id: bosen-pay
            uri: lb://bosen-pay
            predicates:
              - Path=/bosen-pay/**
            filters:
              - StripPrefix=1
        - id: bosen-order
            uri: lb://bosen-order
            predicates:
              - Path=/bosen-order/**
            filters:
              - StripPrefix=1
        - id: bosen-product
            uri: lb://bosen-product
            predicates:
              - Path=/bosen-product/**
            filters:
              - StripPrefix=1
        - id: bosen-marketing
            uri: lb://bosen-marketing
            predicates:
              - Path=/bosen-marketing/**
            filters:
              - StripPrefix=1
        - id: bosen-system
            uri: lb://bosen-system
            predicates:
              - Path=/bosen-system/**
            filters:
              - StripPrefix=1
        - id: bosen-seckill
            uri: lb://bosen-seckill
            predicates:
              - Path=/bosen-seckill/**
            filters:
              - StripPrefix=1
        - id: bosen-after-sales
            uri: lb://bosen-after-sales
            predicates:
              - Path=/bosen-after-sales/**
            filters:
              - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8201/bosen-auth/rsa/publicKey' #配置RSA的公钥访问地址
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/*/swagger-ui.html"
      - "/*/v2/api-docs"
      - "/*/*.js"
      - "/*/*.css"
      - "/*/*.png"
      - "/*/*.ico"
      - "/webjars/**"
      - "/actuator/**"
      - "/bosen-auth/oauth/**"
      - "/bosen-auth/rsa/publicKey"
      - "/bosen-search/**"
      - "/bosen-member/portal/member/login"
      - "/bosen-member/portal/member/register"
      - "/bosen-member/portal/member/getAuthCode"
      - "/bosen-member/home/**"
      - "/bosen-member/product/**"
      - "/bosen-member/brand/**"
      - "/bosen-admin/admin/login"
      - "/bosen-admin/admin/updatePassword"
      - "/bosen-admin/admin/register"
      - "/bosen-admin/minio/upload"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
# 以下配置避免nacos疯狂打印日志
logging:
  level:
    com:
      alibaba:
        nacos:
          client:
            naming: warn