
server:
  port: 8401
spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://sg.mysql.gaofeicm.cf/bosen?sslMode=VERIFY_IDENTITY
    username: nzmbw2azd5pde1ltkwed
    password: pscale_pw_C74y4yxA7OFGZuolfv8eITwkTKhYkwJIvjOZGLAOgjv
  redis:
    host: localhost # Redis服务器地址
    database: 1 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: basic
# 以下配置避免nacos疯狂打印日志
logging:
  level:
    com:
      alibaba:
        nacos:
          client:
            naming: warn